- name: Create Azure Ubuntu Web VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ubuntuwebvmrg
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ubuntuwebvmrg
      name: ubuntuvnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ubuntuwebvmrg
      name: ubuntusubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: ubuntuvnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ubuntuwebvmrg
      allocation_method: Static
      name: ubuntuPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH and HTTP
    azure_rm_securitygroup:
      resource_group: ubuntuwebvmrg
      name: ubuntuNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
        - name: HTTP
          protocol: Tcp 
          destination_port_range: 80  
          access: Allow  
          priority: 102 
          direction: Inbound
        - name: HTTPS
          protocol: Tcp 
          destination_port_range: 443 
          access: Allow  
          priority: 103 
          direction: Inbound
        - name: RDP
          protocol: Tcp 
          destination_port_range: 443 
          access: Allow  
          priority: 104
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: ubuntuwebvmrg
      name: ubuntuNIC
      virtual_network: ubuntuvnet
      subnet: ubuntusubnet
      public_ip_name: ubuntuPublicIP
      security_group: ubuntuNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ubuntuwebvmrg
      name: ubuntuwebvm1
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Password0134!
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDn4i0NkH4uFL7B87MJBW0TyQcsk99vQNlHyZLJyRielhU2kxy73K4ecOEcYQPu0B58KbQfHM2EooaHbZIDAaZK8K62yaYz5eV7YBMr5TdN9Tw5u1GGT5LrWsOYoHcQtcSnTRbBSWZDFIx5eJWebBxdDh61LbEftyOLg16xsLRIqp6SeAtJANTWNSMCEH96qn4+12eoW8bYQ7flVyR7uyE+7NDKmMaHk0zWUQe0wluHyUnfj15g1tfRvwXyUEMLMagyFrhRh0n/wNBnV8XrX74OjqCseJfh3YnuLxhy4hAmw0di699Q3jTB3xJ8b7yg2NvoAF+lzSkQtiArTjEBVKuv'
      network_interfaces: ubuntuNIC
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 18.04-LTS
        version: latest