
- name: Create Cron Job for Web Server configuration
  hosts: localhost
  connection: local
  tasks:
  - name: Cron Job web server configuration
    cron:
     name: "httpd yml configuration"
     minute: "*"
     hour: "*"
     job: '/usr/bin/ansible-playbook -i /home/azureuser/ansible/contrib/inventory/azure_rm.py /home/azureuser/PartsUnlimitedMRP/Labfiles/AZ-400T05-ImplemntgAppInfra/Labfiles/ansible/httpd.yml --extra-vars "vmname=< your-vm-name >"'

  #- name: 'Ensure an old job is no longer present. Removes any job that is prefixed by "#Ansible: an old job" from the crontab'
   # cron:
    # name: "an old job"
    # state: absent

  #- name: Creates an entry like "PATH=/opt/bin" on top of crontab
    #cron:
     #name: PATH
     #env: yes
     #value: /opt/bin

  #- name: Creates an entry like "APP_HOME=/srv/app" and insert it after PATH declaration
    #cron:
     #name: APP_HOME
     #env: yes
     #value: /srv/app
     #insertafter: PATH
